### PR TITLE
Option to fail or pass the action based on results

### LINKED ISSUE #20: Hide the Docker clone logs
Unless they fail for some reason?
Just to make the logs less chatty.

### LINKED ISSUE #31: Option to fail or pass the action based on alerts
Currently, the action fails if it finds any alerts in the report. This will trigger an email for the failed action. It will be good to make this behavior configurable.

```yaml
  fail_action:
    description: 'Fail or pass the action based on alerts'
    required: false
    default: false
```

### PR DESCRIPTION
**Pull request by sshniro**
Fix #31 Fix #20  

Example of a passed action: https://github.com/voicepad/action-baseline/actions/runs/164572104
Example of a failed action: https://github.com/voicepad/action-baseline/actions/runs/164577575

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -39,7 +40,12 @@ async function run() {
         try {
             await exec.exec(command);
         } catch (err) {
-            core.setFailed('The ZAP Baseline scan has failed, starting to analyze the alerts. err: ' + err.toString());
+            if (failAction == 'true') {
```
Comment (thc202) [inline index.js:43]: We should fail the action always when the exit code is 3, that means there's a problem with the script/scan itself (e.g. scan not properly configured or an error while running the script). In that case there's probably no point processing the report (there shouldn't be any).

**Comment by thc202** [comment]
Could you update the changelog?

File: action.yml [hunk 2]
```diff
@@ -25,6 +25,10 @@ inputs:
     description: 'The title for the GitHub issue to be created'
     required: false
     default: 'ZAP Scan Baseline Report'
+  fail_action:
+    description: 'Fail or pass the action based on identified alerts'
+    required: false
+    default: false
```
Comment (psiinon) [inline action.yml:31]: Doesnt this change how the action currently works? I think we should stick to the same default behaviour

File: action.yml [hunk 3]
```diff
@@ -25,6 +25,10 @@ inputs:
     description: 'The title for the GitHub issue to be created'
     required: false
     default: 'ZAP Scan Baseline Report'
+  fail_action:
+    description: 'Fail or pass the action based on identified alerts'
```
Comment (psiinon) [inline action.yml:29]: "Fail or pass" I'm not sure this is clear ;)

File: index.js (hunk 1 above)
Comment (psiinon) [inline index.js:43]: case ignore match? Should we report if its not something we expect?

File: action.yml (hunk 2 above)
Comment (sshniro) [reply action.yml:31]: Yes, this changes the behavior, the previously failed alerts will start to pass with the new version. Sure, I'll revert to the previous behavior.

Comment (thc202) [reply action.yml:31]: Not failing the action by default seems more appropriate, an issue is raised (or updated) with the results so the user is already being informed of the outcome. I'm starting to wonder if we really need to provide this option (and just fail when there's an issue in the script/scan and not in the number of alerts).

File: index.js (hunk 1 above)
Comment (sshniro) [reply index.js:43]: @thc202 is there a way to simulate the code 3 behavior for testing?

Comment (thc202) [reply index.js:43]: The simplest is to pass a target that's not `http` or `https`.

File: action.yml (hunk 2 above)
Comment (sshniro) [reply action.yml:31]: Agreed, the reason to open this issue was Github continuously sending emails for the failed actions (Even though the alerts are the same).

File: action.yml (hunk 3 above)
Comment (sshniro) [reply action.yml:29]: How about `The action status will be set to fail if ZAP identifies alerts during the baseline scan.`

Comment (thc202) [reply action.yml:29]: That looks good to me.

**Comment by sshniro** [comment]
Fixes #20

File: index.js (hunk 1 above)
Comment (sshniro) [reply index.js]: Fixed

Comment (sshniro) [reply index.js]: Fixed

File: action.yml (hunk 2 above)
Comment (sshniro) [reply action.yml:31]: @psiinon any update on this decision ?

File: action.yml (hunk 3 above)
Comment (sshniro) [reply action.yml]: Done

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,6 +4,8 @@ All notable changes to this GitHub action will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ## [Unreleased]
+- Option to fail the status of the GitHub action if any alerts are found during the scan process. [#31](https://github.com/zaproxy/action-baseline/issues/31)
```
Comment (thc202) [inline CHANGELOG.md:7]: Add `### Added` before and `### Changed` after.

File: README.md [hunk 5]
```diff
@@ -42,6 +42,11 @@ Make sure to checkout the repository (actions/checkout@v2) to provide the ZAP ru
 **Optional** ZAP action uses the default action token provided by GitHub to create and update the issue for the baseline scan.
 You do not have to create a dedicated token. Make sure to use the GitHub's default action token when running the action(`secrets.GITHUB_TOKEN`).
 
+### `fail_action`
+
+**Optional** By default ZAP Docker container will fail with an [exit code](https://github.com/zaproxy/zaproxy/blob/develop/docker/zap-baseline.py#L32-L35),
```
Comment (thc202) [inline README.md:47]: We should link to actual commit (or tag), otherwise this might break (e.g. branch renamed, docs/code moved around).

File: index.js [hunk 6]
```diff
@@ -39,7 +45,19 @@ async function run() {
...
-            core.setFailed('The ZAP Baseline scan has failed, starting to analyze the alerts. err: ' + err.toString());
+            if (err.toString().includes('exit code 3')) {
+                core.setFailed('failed to scan the target: ' + err.toString());
+                return
+            }
+
+            if ((err.toString().includes('exit code 2') || err.toString().includes('exit code 1'))
+                    && String(failAction).toLowerCase() === 'true') {
+                console.log(`[info] By default ZAP Docker container will fail if it identifies any alerts during the scan!`);
+                core.setFailed('Scan action failed as ZAP has identified alerts or failed to scan the target, ' +
```
Comment (thc202) [inline index.js:56]: Remove `or failed to scan the target.`? That shouldn't happen (I think, per above check).

File: README.md (hunk 5 above)
Comment (sshniro) [reply README.md:47]: Okay, Got the commit: https://github.com/zaproxy/zaproxy/blob/efb404d38280dc9ecf8f88c9b0c658385861bdcf/docker/zap-baseline.py#L31

File: CHANGELOG.md [hunk 7]
```diff
@@ -4,6 +4,11 @@ All notable changes to this GitHub action will be documented in this file.
 The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ## [Unreleased]
+### Added
+- Option to fail the status of the GitHub action if any alerts are found during the scan process. [#31](https://github.com/zaproxy/action-baseline/issues/31)
+
+### Changed
```
Comment (thc202) [inline CHANGELOG.md:10]: Sorry for yet another comment, might worth saying that the action was changed to no longer fail by default on alerts.

File: action.yml (hunk 2 above)
Comment (psiinon) [reply action.yml:31]: OK, I'm good with that - we want the scan to be useful and not annoying. Will we still fail the first time?

Comment (thc202) [reply action.yml:31]: No, but the issue will be raised (so ok?).

File: CHANGELOG.md (hunk 7 above)
Comment (sshniro) [reply CHANGELOG.md:10]: Done

**Comment by thc202** [comment]
Thank you!

File: action.yml (hunk 2 above)
Comment (richAtreides) [reply action.yml:31]: @thc202 totally agree with you. A fail in this context means a fail with the actual script running, e.g, the action itself fails. In this case it runs so the default should be a pass. 

An improved implementation would be to fail based on a param, being if any high, medium or low issues are found. You could then block merges accordingly. However at the moment its just annoying.

I accept that this is all well and good for me to say as a user and not (yet) a contributor, I'm afraid PRing on this is probably a bit out of my depth but I'm happy to help if I can.
